from .uiactionsheet import UIActionSheet
from .uibutton import UIButton
from .uiimageview import UIImageView
from .uilabel import UILabel
from .uinavbar import UINavBar
from .uisearchbar import UISearchBar
from .uisegmentedcontrol import UISegmentedControl
from .uislider import UISlider
from .sliderview import SliderView
from .uiswitch import UISwitch
from .uitabbar import UITabBar
from .uitablecollectionview import UITableCollectionView
from .uitextfieldview import UITextFieldView
from .uiview import UIView
